### ISSUE TITLE
Usage instructions missing in Readme.md

### ISSUE THREAD

**Issue by polline** [RDFstar/RDFstarPGConnectionTools#3]
It would be great to have some instructions on how to run these tools from the command line.

I got stuck after I tried to pull the repo and executed "mvn clean install". I got the following error: 

```
[...]
[INFO] Compiling 3 source files to /home/username/.../RDFstarPGConnectionTools/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/username/.../RDFstarPGConnectionTools/src/test/java/se/liu/ida/rdfstar/pgtools/conversion/PG2RDFStarTest.java:[18,44] cannot find symbol
  symbol:   class LangTurtleStarTest
  location: package se.liu.ida.rdfstar.tools.parser.lang
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.708 s
[INFO] Finished at: 2020-03-24T17:01:28Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project RDFstarPGConnectionTools: Compilation failure
[ERROR] /home/username/.../RDFstarPGConnectionTools/src/test/java/se/liu/ida/rdfstar/pgtools/conversion/PG2RDFStarTest.java:[18,44] cannot find symbol
[ERROR]   symbol:   class LangTurtleStarTest
[ERROR]   location: package se.liu.ida.rdfstar.tools.parser.lang
[ERROR] 
[...]
```

Thanks!

**Comment by hartig** [comment]
Dear @polline ! Sorry for the long the delay. My world is currently upside down and I hardly find the time to attend to requests such as yours. Anyways, here you go.

Thanks for pointing out the compilation issue. I have fixed this problem (see the commit https://github.com/RDFstar/RDFstarPGConnectionTools/commit/5526eddb023ca1cc957b327b9f20872f31f0dbfa) and you should be able to compile now without error messages.

Additionally, I have also added a few compilation-related instructions to the README.md file. Notice that this repo is still very much in a prototype/pre-alpha phase. I hope to get a student again who can help me improving this repo.

**Comment by polline** [comment]
Thanks @hartig ! It works now, the compiling error is fixed. 
Keep up the good work!
